import test from 'node:test';
import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
test('SQL communications: lifecycle, approvals only, superseding, atomic logs, claims, retries and staff RLS',async()=>{
 const db=new PGlite();
 try {
  await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema private;
   create function auth.jwt() returns jsonb language sql as $$select current_setting('request.jwt.claims',true)::jsonb$$;
   create function auth.uid() returns uuid language sql as $$select (auth.jwt()->>'sub')::uuid$$;
   grant usage on schema auth,private to authenticated,service_role;
   create table bookings(id bigint primary key,name text,phone text default '',email text default '',booking_date text,booking_time text,party_size integer,tables text default '',notes text default '',status text default 'confirmed',source text default 'agenda',reminder_status text,booking_type text default 'normale');
   create table booking_history(id bigint generated always as identity primary key,booking_id bigint,action text,old_data jsonb,new_data jsonb,created_at timestamptz default now());
   grant select,insert,update on bookings to authenticated;
   set request.jwt.claims='{"sub":"11111111-1111-1111-1111-111111111111","app_metadata":{"role":"admin"}}';`);
  for(const f of ['booking-status.sql','booking-history.sql','booking-edit.sql','table-conflicts.sql','after-dinner-bookings.sql','booking-requests.sql','agenda-communications.sql'])await db.exec(await readFile(new URL('../supabase/'+f,import.meta.url),'utf8'));
  await db.exec(await readFile(new URL('../supabase/agenda-communications.sql',import.meta.url),'utf8'));
  const date=(await db.query(`select to_char(d,'YYYY-MM-DD') as day from generate_series((now() at time zone 'Europe/Rome')::date+1,(now() at time zone 'Europe/Rome')::date+7,'1 day') d where extract(isodow from d)<>1 limit 1`)).rows[0].day;
  await db.query(`insert into bookings(id,name,phone,email,booking_date,booking_time,party_size) values(1,'Mario Rossi','+393331234567','mario@example.com',$1,'20:00',2),(2,'Senza Email','+393331234568','',$1,'20:00',2)`,[date]);
  const rows=async()=> (await db.query('select * from booking_communications order by id')).rows;
  assert.deepEqual((await rows()).map(r=>r.status),['queued','skipped']);
  await db.exec('set role authenticated');
  const prepare=async(channel)=> (await db.query('select admin_prepare_booking_communication(1,$1) as r',[channel])).rows[0].r;
  assert.equal((await prepare('email')).id,(await rows())[0].id);
  const request=(await db.query(`select admin_create_booking_request(1,'ora','"20:30"') as r`)).rows[0].r;
  assert.equal((await rows()).length,2);
  await db.query(`select admin_review_booking_request($1,'rejected')`,[request.id]);assert.equal((await rows()).length,2);
  const approved=(await db.query(`select admin_create_booking_request(1,'ora','"20:30"') as r`)).rows[0].r;
  await db.query(`select admin_review_booking_request($1,'approved')`,[approved.id]);
  let all=await rows();assert.equal(all[0].status,'superseded');assert.equal(all.at(-1).kind,'updated');assert.equal(all.at(-1).snapshot.booking_time,'20:30');
  assert.equal((await prepare('email')).kind,'updated');assert.equal((await prepare('whatsapp')).status,'opened');
  const updated=all.at(-1).id;
  await assert.rejects(db.query('select claim_booking_email($1)',[updated]),/permission denied/);
  await assert.rejects(db.exec(`update booking_communications set status='accepted'`),/permission denied/);
  await db.exec('reset role;set role service_role');
  const claim=async()=> (await db.query('select claim_booking_email($1) as r',[updated])).rows[0].r;
  assert.equal((await claim()).status,'sending');assert.equal(await claim(),null);
  await db.query(`select finish_booking_email($1,'failed',null,'provider_http_422')`,[updated]);
  assert.equal((await claim()).attempts,2);
  await db.query(`select finish_booking_email($1,'accepted','provider-id',null)`,[updated]);assert.equal(await claim(),null);
  await db.exec('reset role;set role authenticated');
  const cancel=(await db.query(`select admin_create_booking_request(1,'cancellazione',null) as r`)).rows[0].r;
  await db.query(`select admin_review_booking_request($1,'approved')`,[cancel.id]);
  all=await rows();assert.equal(all.at(-1).kind,'cancelled');assert.equal(all.at(-1).status,'queued');
  assert.ok((await db.query('select * from booking_communication_logs where communication_id=$1',[updated])).rows.some(r=>r.status==='accepted'&&r.provider_id==='provider-id'));
  await db.exec(`set request.jwt.claims='{"sub":"11111111-1111-1111-1111-111111111111","app_metadata":{"role":"customer"}}'`);
  assert.equal((await rows()).length,0);await assert.rejects(prepare('email'),/riservato/);
  await db.exec('reset role');
  const count=(await rows()).length;
  await db.exec('begin;insert into bookings(id,name,booking_date,booking_time,party_size,email) values(3,\'Rollback\',\'2026-10-15\',\'20:00\',2,\'x@example.com\');rollback;');
  assert.equal((await rows()).length,count);
 }finally{await db.close();}
});
